# Generated by Django 5.2.7 on 2025-12-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
    ]
