# Generated by Django 5.2.7 on 2025-12-08 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_seattype_alter_seat_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='SeatType',
        ),
    ]
