# Generated by Django 5.2.7 on 2025-12-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_delete_seat_delete_seattype'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='vip_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='vvip_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
