# Generated by Django 5.2.7 on 2025-12-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_vip_price_remove_event_vvip_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seattype',
            name='total_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
