# Generated by Django 5.2.7 on 2025-12-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_seattype_total_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seattype',
            name='total_seats',
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
