# Generated by Django 5.2.7 on 2025-12-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_seattype_total_seats_event_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seattype',
            name='seats_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seattype',
            name='total_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
