# Generated by Django 5.2.7 on 2025-12-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
