# Generated by Django 5.2.7 on 2025-12-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_delete_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seattype',
            options={},
        ),
    ]
