# Generated by Django 5.2.7 on 2025-12-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_seattype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seattype',
            options={'ordering': ['price']},
        ),
        migrations.AddField(
            model_name='event',
            name='allow_any_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='max_distance_km',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
