# Generated by Django 5.2.7 on 2025-12-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_seattype_options_event_allow_any_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='allow_any_location',
            new_name='allow_any_country',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_distance_km',
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(default='Nepal', max_length=100),
        ),
    ]
