# Generated by Django 5.2.7 on 2025-12-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_rename_allow_any_location_event_allow_any_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
