# Generated by Django 5.2.7 on 2025-12-19 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_category_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='remarks',
        ),
    ]
