# Generated by Django 5.2.7 on 2025-12-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('VIP', 'VIP'), ('VVIP', 'VVIP')], default='GENERAL', max_length=10),
        ),
    ]
