# Generated by Django 5.2.7 on 2025-12-08 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_seat_type'),
        ('events', '0008_remove_event_vip_price_remove_event_vvip_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='events.seattype'),
        ),
    ]
